name: Deploy Website ke Pages

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # Cek apakah folder www ada
      - name: Cek folder www
        run: |
          if [ -d "www" ]; then
            echo "Folder www ditemukan"
            ls -la www
          else
            echo "Folder www TIDAK ditemukan!"
            exit 1
          fi

      # Deploy ke branch gh-pages
      - name: Deploy ke gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./www
          publish_branch: gh-pages
          force_orphan: true   # membersihkan branch gh-pages agar hanya berisi file terbaru
